---
tracing_override: ~
data_root_path: "/var/lib/holochain/data"
device_seed_lair_tag: ~
danger_generate_throwaway_device_seed: false
keystore:
  type: lair_server
  connection_url: ~ # Will be filled by setup script
dpki:
  dna_path: null
  network_seed: ''
  allow_throwaway_random_dpki_agent_key: false
  no_dpki: true
admin_interfaces:
  - driver:
      type: websocket
      port: 8800
      allowed_origins: "*"
network:
  type: NetworkConfig
  bootstrap_url: https://dev-test-bootstrap2.holochain.org/
  signal_url: wss://dev-test-bootstrap2.holochain.org/
  webrtc_config:
    iceServers:
      - urls:
          - stun:stun.l.google.com:19302
      - urls:
          - stun:stun.cloudflare.com:3478
  target_arc_factor: 1
  advanced: null
db_sync_strategy: Resilient
tuning_params: null
tracing_scope: null
