---
tracing_override: ~
data_root_path: "/var/lib/holochain/data"
keystore:
  type: lair_server
  connection_url: ~ # Will be filled by setup script
admin_interfaces:
  - driver:
      type: websocket
      port: 8800
      danger_bind_addr: ~
      allowed_origins: "*"
network:
  base64_auth_material_bootstrap: ~ # Will be filled by setup script
  base64_auth_material_relay: ~ # Will be filled by setup script
  bootstrap_url: https://hc-auth-iroh-unyt.holochain.org/
  signal_url: http://not-used:1234
  relay_url: https://iroh-relay-unyt.holochain.org
  target_arc_factor: 1
  advanced: null
  request_timeout_s: 60
db_sync_strategy: Fast
tuning_params: null
tracing_scope: null
